version: '3'
services:
  web:
      build: .
      command: python3 manage.py runserver 0.0.0.0:8000
      volumes:
        - static_data:/movieapp/static
      ports:
           - 8000:8000
      environment:
        - API_KEY = ${API_KEY}
      env_file:
        - ./.env
      restart: "always"
      depends_on:
        - db

  db:
    image: postgres:14-alpine
    restart: "always"
    volumes:
      - postgres_data:/var/lib/postgresql/data:rw
    env_file:
      - .env
    ports:
      - '5434:5434'
    environment:
      - POSTGRES_DB=${NAME}
      - POSTGRES_USER=${USER}
      - POSTGRES_PASSWORD=${PASSWORD}

volumes:
  static_data:
  postgres_data:

